[package]
name = "cargo-offload"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "offload"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
